name: Deploy solwyz-client

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: solwyz-client
      cancel-in-progress: true

    env:
      IMG_TAG: ${{ github.sha }}
      TARFILE: solwyz-client_${{ github.sha }}.tar

    steps:
    - uses: actions/checkout@v4

    - name: Build frontend image
      run: docker build -t solwyz-client:${{ env.IMG_TAG }} .

    - name: Save image to tarball
      run: |
        docker save solwyz-client:${{ env.IMG_TAG }} -o ${{ env.TARFILE }}
        chmod 644 ${{ env.TARFILE }}

    - name: Copy tar to droplet
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ${{ env.TARFILE }}
        target: ~/app/frontend/

    - name: Load & restart solwyz-client
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/app/frontend
          docker load -i ${{ env.TARFILE }}

          docker stop solwyz-client || true && docker rm solwyz-client || true

          docker run -d \
            --name solwyz-client \
            -p 3000:80 \
            --restart unless-stopped \
            solwyz-client:${{ env.IMG_TAG }}

          rm -f ${{ env.TARFILE }}
          docker image prune -f --filter "dangling=true"
